// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MdiArrowDown: typeof import('~icons/mdi/arrow-down')['default']
    MdiArrowDownThick: typeof import('~icons/mdi/arrow-down-thick')['default']
    MdiArrowUpDown: typeof import('~icons/mdi/arrow-up-down')['default']
    MdiArrowUpDownBoldOutline: typeof import('~icons/mdi/arrow-up-down-bold-outline')['default']
    MdiArrowUpThick: typeof import('~icons/mdi/arrow-up-thick')['default']
    MdiBookOpenOutline: typeof import('~icons/mdi/book-open-outline')['default']
    MdiCheckboxBlankOutline: typeof import('~icons/mdi/checkbox-blank-outline')['default']
    MdiCheckboxMarkedOutline: typeof import('~icons/mdi/checkbox-marked-outline')['default']
    MdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    MdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    MdiLogout: typeof import('~icons/mdi/logout')['default']
    MdiPencil: typeof import('~icons/mdi/pencil')['default']
    MdiUserOutline: typeof import('~icons/mdi/user-outline')['default']
  }
}
