/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MdiCheckboxBlankOutline: typeof import('~icons/mdi/checkbox-blank-outline')['default']
    MdiCheckboxMarkedOutline: typeof import('~icons/mdi/checkbox-marked-outline')['default']
    MdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    MdiPencil: typeof import('~icons/mdi/pencil')['default']
    RiBook2Line: typeof import('~icons/ri/book2-line')['default']
    RiBookReadLine: typeof import('~icons/ri/book-read-line')['default']
    RiLogoutCircleLine: typeof import('~icons/ri/logout-circle-line')['default']
    RiTeamLine: typeof import('~icons/ri/team-line')['default']
  }
}
