import { Schueler } from './Schueler'

export interface Leistung {
	id: number,
	klasse: string|Number|null,
	name: string,
	vorname: string,
	nachname: string,
	geschlecht: string,
	fach: string|null,
	fach_id: number|null,
	lehrer: string,
	jahrgang: string,
	kurs: string|null,
	note: string|null,
	fachbezogeneBemerkungen: string|null,
	fehlstundenGesamt: Number,
	fehlstundenUnentschuldigt: Number,
	fs: number,
	ufs: number,
	istGemahnt: boolean,
	mahndatum: string,
	schueler: Schueler,
	matrix: {
		editable_teilnoten: boolean, 
		editable_noten: boolean, 
		editable_mahnungen: boolean, 
		editable_fehlstunden: boolean, 
		editable_fb: boolean, 
		editable_asv: boolean, 
		editable_aue: boolean, 
		editable_zb: boolean, 
	},
}